name: BlueRoseCommons
main: io.github.dre2n.commons.BlueRose
version: ${project.version}
authors: [Daniel Saukel, Frank Baumann, Milan Albrecht]
description: ${project.description}
website: ${project.url}
softdepend: [Vault]
